<?php

function read_define($file, $filter) {
    $lines = file($file);
    $result = array();
    echo "+{$file}\n";

    foreach ($lines as $line) {
        $line = trim($line);

        if (0 === strpos($line, '#define ')) {
            $parts = preg_split("/\s/s", $line);

            if (count($parts) > 2) {
                $result[] = $filter($parts[1], $parts[2]);
                echo "-{$parts[1]}\n";
            }
        }
    }

    return $result;
}

function camel_str($str) {
    return lcfirst(str_replace(' ', '', ucwords(implode(' ', explode('_', strtolower($str))))));
}

$result = "// these constants is generated by tools
var _ = {\n";

// parse SciLexer.h
read_define('../scintilla/include/SciLexer.h', function ($key, $val) use (&$result) {
    $result .= "{$key} : {$val},\n";
});

// parse SciLexer.h
read_define('../scintilla/include/Scintilla.h', function ($key, $val) use (&$result) {
    if (ctype_digit($val)) {
        $result .= "{$key} : {$val},\n";
    } else if (0 === strpos($val, '0x')) {
        $val = hexdec(substr($val, 2));
        $result .= "{$key} : {$val},\n";
    }
});


$result = substr($result, 0, -2) . "\n};\n\n" . file_get_contents(__DIR__ . '/init.js');
file_put_contents(__DIR__ . '/../typeditor/init.js', $result);

